jupyter_nbformat/sign.py
jupyter_nbformat/tests/base.py
jupyter_nbformat/tests/test_sign.py
requirements.txt
scripts/jupyter-trust
setup.py

make trust a Jupyter application

---

README.md

Fix link to Jupyter Notebook format

---

docs/requirements.txt

To support building on RTD
Merging directly because I'm fiddling with docs builds now.

Add requirements for docs

---

.travis.yml
requirements.txt

jupyter-core is out

---

nbformat/tests/test_convert.py
nbformat/v4/convert.py

Fix issue 35: v4 conversion failures with 'orig_nbformat_minor'

---

docs/changelog.rst
docs/index.rst

Should be able to release 4.1 after this.

Add changes for 4.1

---

.gitignore
.travis.yml
nbformat/sign.py
nbformat/v4/tests/test_convert.py
nbformat/v4/tests/test_nbbase.py
nbformat/v4/tests/test_validate.py
setup.py

and test on nightly (allow failures)

run tests with pytest

---

.gitignore
nbformat/sign.py
nbformat/tests/test_sign.py
setup.py

decorators, tags
(based on #54)

use traitlets 4.1 API

---

docs/changelog.rst
docs/format_description.rst

document authors metadata, fix attachment example
closes #66

add notes for 4.2

---

docs/changelog.rst

Should be ready to ship 4.2 after this.

add last changelog note for 4.2

---

nbformat/v4/rwbase.py

Minor adjustments for less confusing error messages.

Adjust of NotImplementedError message strings

---

nbformat/__init__.py

Allow file paths to be bytes

---

docs/api.rst
docs/changelog.rst
docs/conf.py
nbformat/sign.py
nbformat/v4/__init__.py

Update the changelog, document the `NotebookNotary` and new `SignatureStore` classes.

Documentation for 4.3 release

---

docs/format_description.rst

This came out of clarifications in conversations at the Spring 2017 Jupyter dev meeting.
CC @minrk, @ellisonbg.

Clarify that metadata fields may be ignored

---

nbformat/sign.py

fix: Check if signature for notebook already exists before inserting

---

docs/changelog.rst

Add changelog note for #107. 
I am likely to merge this as part of the release process.

Release 4.4

---

nbformat/v4/nbbase.py

add default execution_count to None for new_output_cell('execute_result')

---

.travis.yml
nbformat/v2/__init__.py
nbformat/v2/nbxml.py

Leave an explanatory error message on the off chance that anyone is still using it.
Closes gh-132

Remove code for reading notebooks as XML

---

docs/format_description.rst

I couldn't find an explicit reference to the JSON schema in this documentation, so I've added one in this PR

reference to schema

---

.travis.yml

- upgrade setuptools, pip
- pip freeze for debugging
- dist: xenial
- add py3.7

update travis test matrix

---

RELEASING.md

Added in some documentation for releasing the `npm` package, `nbformat-schema`.

include instructions for pushing to npm

---

setup.py

Fixes https://github.com/jupyter/nbformat/issues/162
Tested on python 2 and python 3.4 for install blocking

Added python_requires check for version to prevent python 2 installs

---

nbformat/v4/nbformat.v4.4.schema.json
nbformat/v4/nbformat.v4.schema.json

I think someone forgot to update this number when bumping to format version 4.4.
CC @MSeal

Update the 4.4 schema to apply to minor format at least 4.

---

nbformat/validator.py

This is the continuation of #183.

Fix exception cause in validator.py

---

nbformat/reader.py

Accept bytes

---

setup.py

PR: Add key on setup.py to include data in wheels

---

docs/changelog.rst
nbformat/v4/convert.py
nbformat/v4/tests/test_convert.py

Fixes https://github.com/jupyter/nbformat/issues/196

Changed convert.upgrade to upgrade minor 4.x versions to 4.5

---

.github/workflows/tests.yml
setup.py

Drop EOL Python 3.5 and Python 3.6.
Add testing for Python 3.10.

Update supported python versions

---

.github/workflows/tests.yml
docs/changelog.rst
docs/markup.rst
docs/requirements.txt
pyproject.toml

Also add docs job with warnings handling and link check

Add pyproject.toml file and configure pytest

---

nbformat/json_compat.py
nbformat/validator.py
setup.py

cf https://github.com/jupyter-server/jupyter_server/issues/312

Use fastjsonschema by default

---

.github/workflows/tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md

Make some checks manual and only run on CI by default
Update docs

Clean up pre-commit

---

.github/workflows/tests.yml
nbformat/sign.py
setup.py

- Clean up matrix
- Add additional checks for min versions, pre-releases, and sdist test

Improve CI

---

.github/workflows/tests.yml
docs/changelog.rst

Fix changelog formatting error
Ignore warnings on prerelease build

Fix some CI failures

---

CHANGELOG.md

The current syntax is not supported in MyST

Fix changelog target

---

.github/workflows/tests.yml
nbformat/_version.py
pyproject.toml

Fix version handling

---

nbformat/sign.py
nbformat/validator.py
pyproject.toml
tests/test_sign.py
tests/v4/test_json.py

Fix encoding warnings
