jupyter_nbformat/__init__.py

Document that nbformat.read() expects unicode file handle

---

README.md

was pointing to old IPython docs

fix format doc link in README

---

docs/conf.py
docs/format_description.rst
docs/requirements.txt

- note that it's only *on-disk* that multi-line strings may be split
- add missing `'output_type': 'error'` on error outputs
- use napoleon, not numpydoc

small docs fixes

---

nbformat/tests/test_validator.py
nbformat/validator.py

avoids logging entire notebooks and schemata when errors are found at the top level
nbviewer's logs contain 100s of MB of notebooks for tiny schema errors if those errors are at a high level.
What would include the entire schema and the entire notebook is now:
```
Notebook JSON is invalid: Additional properties are not allowed ('name' was unexpected)
Failed validating 'additionalProperties' in notebook:
On instance:
{'cells': ['...5 cells...'],
'metadata': {'orig_nbformat': 3},
'name': 'wapiti',
'nbformat': 4,
'nbformat_minor': 0}
```
or on a single output:
```
Notebook JSON is invalid: Additional properties are not allowed ('key' was unexpected)
Failed validating 'additionalProperties' in stream:
On instance['cells'][3]['outputs'][0]:
{'key': 'bad', 'name': 'stdout', 'output_type': …
```

truncate validation error messages

---

nbformat/sign.py

Correct docstring - signature database is in data dir, not runtime

---

.travis.yml
nbformat/sign.py
nbformat/tests/test_sign.py
setup.py

- A potential fix for issue #26 which will also address ipython issue 9003.  
- Cannot seem to get the tests to load the invalid db file I've created - any suggestions?

Issue 26: Check and handle errors loading signature db

---

docs/format_description.rst
nbformat/v4/nbbase.py
nbformat/v4/nbformat.v4.schema.json

This is a proposal to add a new 'attachments' property to cells to allow for inline medias.
The primary use case is to be able to add images to markdown cells and store them directly in the notebook (as opposed to having them on the filesystem).
References :
original issue : https://github.com/jupyter/notebook/issues/613 
corresponding notebook PR : https://github.com/jupyter/notebook/pull/621

Add a new attachment property for cells.

---

nbformat/sign.py

This issue was identified in jupyter/jupyter#174, where takluyver suggested something like this solution.  If the `init_db` fails with an `OperationalError`, this assumes that the problem is an I/O error, and tries to initialize the DB again, using the `:memory:` location so that `sqlite` simply creates an in-memory database.

Catch possible I/O error initializing trust DB

---

setup.py

Executing the tests with jsonschema-2.3.0 installed the tests fail with:
```
======================================================================
ERROR: test_validation_error (nbformat.tests.test_validator.TestValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/var/tmp/portage/dev-python/nbformat-4.1.0/work/nbformat-4.1.0/nbformat/tests/test_validator.py", line 61, in test_validation_error
nb = read(f, as_version=4)
File "/var/tmp/portage/dev-python/nbformat-4.1.0/work/nbformat-4.1.0/nbformat/__init__.py", line 141, in read
return reads(fp.read(), as_version, **kwargs)
File "/var/tmp/portage/dev-python/nbformat-4.1.0/work/nbformat-4.1.0/nbformat/__init__.py", line 78, in reads
validate(nb)
File …
```

Raise jsonschema dependency

---

nbformat/tests/test4custom.ipynb
nbformat/tests/test_validator.py
nbformat/v4/nbformat.v4.schema.json

Closes #42.
Otherwise plain JSON objects will make the notebook displeased. Currently if a mime type like this comes across on the message spec, all is fine up until the notebook is saved. nbviewer and nteract handle it fine, jupyter notebook does not:

Allow custom mimetypes with +json suffix

---

nbformat/tests/test4docinfo.ipynb
nbformat/tests/test_validator.py
nbformat/v4/nbformat.v4.schema.json

This adds a document_info object to the schema to hold the title and author of the document.
cc: @minrk @rgbkrk

Add document_info to schema

---

nbformat/tests/test4docinfo.ipynb
nbformat/v4/nbformat.v4.schema.json

since it's an arrary
follow-up to #46

make authors plural

---

.gitignore
nbformat/sign.py
nbformat/tests/test_sign.py

enables `cat notebook | jupyter trust`
closes #27

allow trusting a notebook from stdin

---

nbformat/v4/nbformat.v4.schema.json

Closes https://github.com/jupyter/nbformat/issues/57

Allow top-level arrays for "application/*json" mime type

---

docs/format_description.rst

JSON doesn't allow trailing commas after last entry in list/object specification.

Make attachment example in doc valid JSON

---

nbformat/v4/nbformat.v4.schema.json

Spec remains the same - this updates the description of the notebook format to be the _Jupyter_ notebook format.

Update description with Jupyter name

---

nbformat/v4/convert.py
nbformat/v4/nbbase.py
nbformat/v4/nbformat.v4.schema.json
nbformat/v4/rwbase.py
nbformat/v4/tests/nbexamples.py
nbformat/v4/tests/test_json.py

required some tweaks to split_lines, downgrade 4->3
downgrade 4->3:
- pop output mimes not supported on v3
- pop attachments
split_lines:
- apply split/rejoin to attachments
- avoid rejoining json arrays (related to #62)

exercise attachments, json outputs in v4 tests

---

nbformat/v4/nbformat.v4.schema.json

This allows dashes in `application/*+json` mime types. See https://github.com/frictionlessdata/specs/issues/289 for discussion proposing a mime type with dashes.

Allow `-` in JSON-like mime types

---

docs/format_description.rst

This reverts part of #67.
See also #66 and https://github.com/jupyter/notebook/issues/1655.

DOC: Use proper URL for attachment example

---

nbformat/sign.py
nbformat/tests/test_sign.py

This makes signature storage pluggable at `NotebookNotary.store`, and provides two implementations: 
- `SQLiteSignatureStore` is the default
- `MemorySignatureStore` is a fallback and an example for other implementations.
I'm experimenting with configuring the store as an instance rather than the factory pattern we use elsewhere. This relies on using Python config files, and means that configuration would look like this:
```python
from sqlsigs import MySQLSignatureStore
c.NotebookNotary.store = MySQLSignatureStore('127.0.0.1', database='nbsignatures')
c.NotebookNotary.store_type = 'sqlsigs.MySQLSignatureStore'
c.MySQLSignatureStore.server = '127.0.0.1'
c.MySQLSignatureStore.database = 'nbsignatures'
```

Pluggable signature storage

---

nbformat/tests/base.py

Should close #74 by modifying the base class being used.
Also, for py2/py3 compatibility I changed it to use `io.open` as is done in the rest of the code base.

add encoding to tests base class fopen function

---

nbformat/tests/test_validator.py
nbformat/validator.py

Trying to validate an empty dict would previously throw an AttributeError since `nbformat.v1` doesn't have the `nbformat_minor` attribute.

Fix: Validation of empty dict raised AttributeError

---

nbformat/sign.py
nbformat/tests/test_sign.py

so that db connections can be explicitly closed. It's a no-op in the base class for stores that don't have anything to open.
Discovered by @vidartf because the fact that we don't close db files causes errors during cleanup of the tests on Windows.
also found a few `log.warn`s to update.

Add Store.close

---

MANIFEST.in
index.js
nbformat/_version.py
package.json

The schema files are left unmoved in the npm package. `index.js` loads the schemas with their versions, so you can do:
```javascript
let nbformat = require('nbformat-schema').v4
```
This is just the raw schema JSON, not a validator or anything.
I've uploaded an example build as [minrk-nbformat-schema](https://www.npmjs.com/package/minrk-nbformat-schema).
cc @rgbkrk @SylvainCorlay @blink1073
closes #70

Add files for `nbformat-schema` npm package

---

nbformat/sign.py

In some circumstances, we can fail to connect to the SQLite database without creating the file. Then attempting to move it to the backup location fails as well. This catches that error and falls back to using an in-memory database for signatures.
Closes jupyter/notebook#2621

Catch OSError from renaming non-existant file

---

docs/changelog.rst
docs/format_description.rst
nbformat/tests/test4jupyter_metadata.ipynb
nbformat/tests/test_validator.py
nbformat/v4/nbformat.v4.schema.json

Following discussion from Jupyter Team Meeting, here's a follow on PR for the metadata I'd like to see us standandardize on.
This PR uses `source_hidden` within `.cells[].metadata.input_hidden`, only for code cells (since markdown and raw cells imply hidden by default in most views (I'd be happy to add it to markdown if someone wanted it to be explicit though...)
xrefs:
* https://github.com/jupyter/notebook/issues/534 
* https://github.com/nteract/nteract/pull/1697
/cc @ellisonbg @mpacer @jcb91

declare source_hidden and outputs_hidden official code cell metadata

---

nbformat/validator.py

This arises in the context of determining what sorts of intermediate representations we want for notebooks in nbconvert: https://github.com/jupyter/nbconvert/pull/643
It was suggested by @minrk that we only allow additional fields (and no additional values for existing fields or the deletion of fields) in terms of this intermediate representation.
Up until now, we thought that preprocessors had always only created valid notebooks. That turns out to be not be the case (https://github.com/jupyter/nbconvert/pull/645).
It would be nice to be able to establish that the only things allowed by preprocessors is to exactly what we say it is.
To that end, this adds a flag to the `validate` API (and the `get_validator` API)  for communicating that that specific relaxation is to be adhered to and …

add relaxation flag to validator call

---

docs/changelog.rst
nbformat/_version.py

This is just editing the changelog as part of the releasing process for 4.4.
Some of the changes included in the 4.4 milestone were actually part of the 4.3 release so I added those to the 4.3 notes in the change log.

add notes to changelog

---

nbformat/notebooknode.py
nbformat/v4/nbbase.py
nbformat/v4/nbjson.py

Directly addresses feature in #102. 
only difference from the suggested implementation by @minrk is that I added this to `__setitem__` instead of `__setattr__`. I did this because `__setattr__`  was calling `__setitem__` anyway and this also covers the case where assignment is accomplished standard the standard object["key"] syntax. This is already supported by `NotebookNode` (it inherits from `ipython_genutils.ipstruct.Struct` which is is a dictlike & has a `__setitem__` implementation).
My one concern is that tab completion (in the notebook) is not catching attribute values set in this way (even if they are set using the attribute syntax, which is odd).

Catch dict-like vals in  __setitem__, apply from_dict()

---

nbformat/tests/test_validator.py
nbformat/validator.py

Uses the iter_errors method from jsonschema to allow collecting all validation errors from a notebook in one validation pass.  Prior behavior would halt validation on the first error.
This will allow better user interaction by notifying the user of all the errors in notebook file at one time rather than one-each-time-user-tries-to-reload-notebook.
@minrk Thanks for your help (and sharp eye) in putting together this PR.

Return all validation errors when loading notebook

---

docs/format_description.rst
nbformat/v4/nbformat.v4.schema.json

This just clarifies the use of `cell.metadata.name` in the format. 
Specifically it suggests that it is expected to be unique for all cells in the notebook and it specifies that this uniqueness condition needs something in addition to the schema to check for that fact.
Closes #114

Adds more info about name's meaning for cells

---

nbformat/validator.py

Based on discussion in #112  we should make our docstrings and signatures for `validate` (and `iter_validate`) more straightforward. Currently the argument is called nbjson and the docs call for  notebook JSON (presumed to be a string).  All it will accept in actuality is a nbdict-like object.
This solves this with a few pieces:
1. change the main argument to be named `nbdict` for both `validate` and `iter_validate`
2.  fix the signature & docs for both `validate` and `iter_validate`.
3. avoid backwards compatibility for anyone using the `nbjson` keyword argument (↬@takluyver for pointing this out)
4. allow optional handling of nbjson as a json string by passing it through to `nbformat.reader.reads()` which reads json strings in and passes it back as a dict-like 
a. Note what is passed …

put in logic for handling nbjson kwargs

---

nbformat/tests/test_validator.py
nbformat/validator.py

Fixes https://github.com/jupyter/nbformat/issues/123
Note that this PR changes what nbformat does when asked to validate invalid notebooks with no version. Based on https://github.com/jupyter/nbformat/issues/123#issuecomment-375266782 I think that's OK. My test updates to account for this are isolated in https://github.com/jupyter/nbformat/commit/05582b9185980aef8dd26637f521318de85b7c1e so it should be easy to check if the behaviour changes I'm making are reasonable.

Fail invalid notebook validation

---

nbformat/notebooknode.py

I got the following deprecation warning when I run some tests that using `nbformat` module with `Python 3.7`:
```
.tox/python3.7/lib/python3.7/site-packages/nbformat/notebooknode.py:4
/home/toor/workspace/sqlitebiter/.tox/python3.7/lib/python3.7/site-packages/nbformat/notebooknode.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Mapping
```
This PR aims to avoid the `DeprecationWarning`

Avoid a DeprecationWarning of collections module import

---

docs/format_description.rst

This addresses https://github.com/jupyter/nbformat/issues/47 by documenting the `scrolled` key instead of the `autoscroll` key. Jupyter Notebook doesn't use the autoscroll key and jupyterlab doesn't either.
I came across this as I was implementing persisting scroll/hidden states for cells in JupyterLab (https://github.com/jupyterlab/jupyterlab/pull/3981)

Change metadata key scrolled to autoscrolled

---

docs/format_description.rst

I believe this is how it works in Jupyter classic.  I'm going to submit another PR with how it works in JupyterLab.  Please accept one of them!   I vote for the Jupyter classic behavior, but will implement whichever approach is accepted in CoCalc, unless you wait too long to decide (since I don't want to confuse users by switching back and forth).
closes #143

document the editable metadata flag

---

nbformat/tests/test4jupyter_metadata_timings.ipynb
nbformat/tests/test_validator.py
nbformat/v4/nbformat.v4.schema.json

Ref: https://github.com/jupyterlab/jupyterlab/pull/5009

Add execution timings in code cell metadata for v4 spec

---

docs/conf.py
docs/index.rst
docs/markup.rst

This adds a short page that describes some of the Markdown rendering behavior. It's just meant to be a description of the current state of things, rather than formalizing anything new. As such it is a bit hand-wavy about some things, which (I think) is an accurate reflection of Jupyter's current treatment of markdown.
(also two minor documentation config fixes)
Partially addresses #96

adding documentation about markup used

---

.travis.yml
README.md
RELEASING.md
appveyor.yml
docs/changelog.rst
nbformat/__init__.py
nbformat/sign.py
nbformat/v1/nbbase.py
nbformat/v2/nbbase.py
nbformat/v2/nbpy.py
nbformat/v2/rwbase.py
nbformat/v3/nbbase.py
nbformat/v3/nbjson.py
nbformat/v3/rwbase.py
nbformat/v3/tests/test_json.py
nbformat/v3/tests/test_misc.py
nbformat/v4/nbjson.py
nbformat/v4/rwbase.py
nbformat/v4/tests/test_json.py
setup.py

Addresses https://github.com/jupyter/nbformat/issues/150. The changes in the PR are documentation, setup.py, and anything that was obviously safe to change for python 3 only support (`py3compat` imports that had no logic associated). 
I left the actual version bump out of the PR direct but added the bumpversion instructions to the `RELEASING.md` file that I will execute once this merges.
nbform schema bumps to 4.5.0 with this release. The changes included some schema changes so it warrants a bump.
Apologies my editor cleaned up some file's whitespacing so the diff is longer.

Removal of support for python 2 and prep for 5.0 release

---

docs/format_description.rst

A user noticed this wasn't updated in the read-the-docs. Doesn't need a release but will explain the schema changes and how to interpret them.

Added missing cell execution docs for new schema

---

docs/changelog.rst
nbformat/v4/nbformat.v4.1.schema.json

There are a number of people posting issues with nbformat 5 being stricter about validating notebook format 4.1, including:
https://github.com/jupyter/nbformat/issues/160
https://github.com/jupyter/nbformat/issues/161
https://github.com/jupyter-widgets/ipywidgets/issues/2553
https://github.com/jupyter-widgets/ipywidgets/issues/2788
Essentially, nbformat package version 4.x allowed noncompliant format 4.1 notebooks to be verified as valid, leading to many notebooks in the wild having major/minor format version 4.1, but with widgets and other json outputs that were technically invalid.
Upgrading to nbformat package 5.x correctly flagged these notebook as noncompliant. This is correct technically. However, practically it means that all these notebooks files tagged as format 4.1 that were …

Allow notebook format version 4.1 mimebundle keys ending in `+json` to have arbitrary JSON

---

docs/changelog.rst
nbformat/v4/nbformat.v4.0.schema.json

See https://github.com/jupyter/nbformat/pull/167 for more discussion. Essentially, there are a lot of notebooks in the wild that have arbitrary JSON in the mimebundles (for example, from ipywidgets), and we never flagged them before, but with nbformat package 5, they are now suddenly they are flagged as noncompliant.
This is a follow-up to https://github.com/jupyter/nbformat/pull/167, and extends the compatibility changes from 4.1 back to 4.0.

Allow notebook format 4.0 to have arbitrary JSON in mimebundle keys ending with +json.

---

nbformat/__init__.py
nbformat/tests/test_api.py

Switching this to a try/except model seems to follow the python 'duck-typing' ethos -- i don't really care about the type of `fp`, i only care what i can do with it:
1. I'll try reading/writing (supports any file-like object)
2.  if step 1 that doesn't work, i'll try opening fp and *then* reading / writing (supports any path-like object that can be opened)
i tried this out locally and it seemed to work both with a `Path` object and a string containing the path 
fixes #147

Support reading/writing path-like objects

---

nbformat/__init__.py
nbformat/tests/test_nbformat.py

This PR aims to fix backward compatibility of an error handling.
At `nbformat 5.0.5`, `nbformat.read` method raises `TypeError` that is a different exception from `nbformat 5.0.4` or older (`AttributeError`) when executing the method with an invalid notebook file.
The following source code can reproduce the issue:
```py
import nbformat
ipynb_file = "empty.ipynb"
with open(ipynb_file, "w") as fp:
fp.write("{}")
with open(ipynb_file) as fp:
nbformat.read(fp, as_version=4)
```
Until `nbformat 5.0.4` or older versions, this results `AttributeError`.
...
.../ipython_genutils/ipstruct.py", line 134, in __getattr__
raise AttributeError(key)
However, `nbformat 5.0.5` will raise `TypeError`:
...
.../nbformat/__init__.py", line 140, in read
with io.open(fp, encoding='utf-8') as f:
TypeError: …

Fix backward compatibility of an error handling

---

nbformat/tests/test_validator.py

I got the following DeprecationWarning in Python 3.5+ when running tests.
```
py::TestValidator::test_validation_error
.../nbformat/nbformat/tests/test_validator.py:98: DeprecationWarning: Please use assertRegex instead.
self.assertRegexpMatches(s, "validating.*required.* in markdown_cell")
nbformat/tests/test_validator.py::TestValidator::test_validation_error
.../nbformat/nbformat/tests/test_validator.py:99: DeprecationWarning: Please use assertRegex instead.
self.assertRegexpMatches(s, "source.* is a required property")
nbformat/tests/test_validator.py::TestValidator::test_validation_error
.../nbformat/nbformat/tests/test_validator.py:100: DeprecationWarning: Please use assertRegex instead.
self.assertRegexpMatches(s, r"On instance\[u?['\"].*cells['\"]\]\[0\]")
```
This PR will fix …

Fix DeprecationWarning

---

nbformat/validator.py

Attempting to call `get_validator()` without arguments led to an ImportError:
```
In [1]: from nbformat.validator import get_validator
In [2]: get_validator()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-0ba64c184823> in <module>
----> 1 get_validator()
~/nbformat/nbformat/validator.py in get_validator(version, version_minor, relax_add_props)
55     """Load the JSON schema into a Validator"""
56     if version is None:
---> 57         from .. import current_nbformat
58         version = current_nbformat
59
ValueError: attempted relative import beyond top-level package
```
This fixes that bug
```
In [1]: from nbformat.validator import get_validator
In [2]: …
```

Fix get_validator()

---

nbformat/reader.py

I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now, there is one other file with this issue.
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The …

Fix exception cause in reader.py

---

.github/workflows/tests.yml
README.md
docs/api.rst
docs/changelog.rst
nbformat/__init__.py
nbformat/json_compat.py
nbformat/tests/base.py
nbformat/tests/many_tracebacks.ipynb
nbformat/tests/test_validator.py
nbformat/validator.py
setup.py

Fixes #190
This adds the possibility of using [fastjsonschema](https://github.com/horejsek/python-fastjsonschema/) if installed and other libraries if installed or defined by a `NBFORMAT_VALIDATOR` environment variable.
The possible values are 1-1 to the module names so, `jsonschema`, `fastjsonschema`, eventually (when stable) we could also add `jsonschema_rs`, the rust implementation.
- Added a tests to check things work as expected with both libraries, with one caveat: test that expect a `better_error` will not work, so those 2 tests are skipped for `fastjsonschema`. The rest works as expected. This means if using `fastjsonschema` printed errors will be less readable.
- Update CI configuration.
- Used pytest parametrize
Related to https://github.com/jupyter/jupyter_server/issues/312 …

PR: Use fastjsonschema if installed and add tests

---

nbformat/json_compat.py
nbformat/tests/test_validator.py

Fixes #197 
This fixes a regression introduced when using fastjsonschema, which does not directly support to validate a "reference"/"subschema". For these cases, `iter_errors`  falls back to the default validator that uses json schema.

PR: Fallback to default validator if subschema is provided

---

.bumpversion.cfg
.github/scripts/create_npmrc.py
.github/scripts/parse_ref.py
.github/workflows/release_publish.yml
.github/workflows/tests.yml
.gitignore
MANIFEST.in
RELEASING.md
nbformat/_version.py
package.json
setup.py

- Simplify release process with package publishing on CI
- Adds a check-manifest step
- Uses bump2version (the maintained fork)

PR: Add CI workflow for package release on tag push

---

.github/scripts/parse_ref.py
.github/workflows/release_publish.yml
RELEASING.md

- This fix the set-env deprecated behavior from CI workflows.
- Updates the RELEASE.md instructions.

PR: Update release instructions and scripts for CI release workflows

---

setup.py

Fix package_data declarations in setup.py to associate every set
of files with its bottommost package.  This is necessary for the 'build'
command to install files correctly when --build-base is passed
explicitly.  The all-files-for-top-package approach seems to work only
incidentally.
To reproduce the problem, try:
setup.py build --build-base=build2
and note that none of the data files were installed.

Fix installing package_data when --build-base is set

---

nbformat/corpus/tests/test_words.py
nbformat/corpus/words.py

to avoid deprecation warnings under Python 3.9.1
May fix #212

Store words in a list (rather than in a set)

---

nbformat/v4/convert.py

The bare return statement returns None by default. If nothing is to be upgraded, the original notebook should be returned.

Return the notebook when no conversion is needed

---

.github/workflows/tests.yml
setup.py

It is not actually required to run the tests.
It is only used when explicitly enabled via the --cov option,
e.g. on GitHub actions, where we install the package manually now.
In Fedora, we don't run the tests with --cov, so we don't need the dependency.

Don't list pytest-cov as a test dependency

---

nbformat/tests/no_min_version.ipynb
nbformat/tests/test_validator.py
nbformat/v4/convert.py
nbformat/v4/tests/test_convert.py

Motivation:
- We have seen a number of notebooks which do not contain the nbformat
minor version, this throws a key error when trying to update. This
pr adds a check to ensure it is present and throws a validation error
if not.

Ensure nbformat minor version is present when upgrading

---

.github/workflows/tests.yml
.gitignore
MANIFEST.in
nbformat/tests/test_validator.py
nbformat/tests/v4_5_no_cell_id.ipynb
nbformat/validator.py

Adds a new kwarg to validate called `repair` which will fix well-known validation errors during the validation process, but only when set to `True`.
Updates existing functionality to not mutate the notebook contents, but instead fail validation.
See: #243, #235

Only fix cell ID validation issues if asked

---

nbformat/json_compat.py
nbformat/tests/test_validator.py
nbformat/tests/v4_5_invalid_metadata.ipynb
nbformat/validator.py

This adds a kwarg to `validate`: `strip_invalid_metadata`, which when set to True will introspect into schema failures during validation and will attempt to remove top-level metadata keys for the cell or notebook that are failing validation.
Specifically what this mechanism does:
1. Converts ValidationErrors into an ErrorTree so we can traverse the schema
2. Removes all top-level metadata keys that failed validation
3. Iterates through all validation errors at the cell level
4. Identifies what the intended cell_type was for that cell
5. Removes all top-level metadata that had a validation error _specific_ to the intended cell_type
Potential issues that might block merging this as-is:
1. There is some slight fragility around determining the intended cell type schema `schema_index = …

Strip metadata that is causing notebook validation to fail

---

.gitignore
nbformat/__init__.py
nbformat/tests/test_api.py

This pull request stems from an issue discovered during Jupyter Server performance analysis in which it was learned that the [server is validating notebooks twice ](https://github.com/jupyter-server/jupyter_server/issues/312#issuecomment-697081912)(and on both read and write operations).  The crux of the issue is that both methods do not give the caller information regarding the validation status of their content - so they must explicitly validate a second time.  This appears to have been the case for the last 7 to 8 years (since the code resided in notebook).  I suspect this is based on decisions at the time, but this pull request attempts to rectify this in a (hopefully) acceptable manner.  Since the elimination of the redundant validation can improve performance by nearly 50%, this …

Add ability to capture validation errors

---

.github/workflows/release_publish.yml

We need write permissions on the contents to create a GitHub release per their [example](https://github.com/ncipollo/release-action#example)

Fix publish workflow

---

.github/workflows/tests.yml
nbformat/corpus/tests/test_words.py
nbformat/current.py
nbformat/json_compat.py
nbformat/v3/nbbase.py
nbformat/validator.py
setup.py
tests/test_validator.py
tests/v3/test_nbbase.py

- for #255
- `ErrorTree` was basically broken before this

Increase minimum jsonschema to 2.6, handle warnings

---

.bumpversion.cfg
setup.py

Adding project URLs (especially source code URL) makes it easier for dependency management tools (like Renovate).

Add project URLs to setup.py

---

nbformat/current.py

`warnings` don't have `warning` method, but have `warn` https://docs.python.org/3/library/warnings.html#warnings.warn

Fix import nbformat.current

---

docs/changelog.rst
nbformat/current.py
nbformat/json_compat.py
nbformat/validator.py
nbformat/warnings.py
tests/test4.5.ipynb
tests/test_validator.py

Re-issue of #236. #244 made things even worse with respect to some problem with notebook trust, 
where a notebook is trusted, saved, reopened  but is not trusted. 
The reason being that the signature is computed before validate, and validate mutate the notebook, leading to the signature not matching. 
really `validate()` _should not mutate the notebook ever_. Validate is in part used for security. It should not return a value of give results on a modified object. 
Just try to imagine if a password comparison function, said `compare('HUNTER@', 'hunter2') == True` because obviously the user had caps lock pressed on their keyboard ? This is the same.
We obviously can't change brutally, but we really need to stop having validation and normalisation be the same step.

Start separating normalisation from validation logic

---

pyproject.toml

I noticed `url` had `http://`. [nbclient](https://github.com/jupyter/nbclient/blob/main/setup.py#L37) has it correct plus http on jupyter.org is redirected to https.

Fix url in setup_args to https

---

.bumpversion.cfg
.pre-commit-config.yaml
nbformat/_version.py
pyproject.toml
tests/test_api.py

Pep 440 mandate that the makers are `a`, `b`, `rc`, without dots.
Not beta/alpha. And `.dev` if present, must have a dot.
Otherwise this leads to problem in package resolutions where tgz can
appear to be more recent than whl of the same version...
This try to fix the version numbering scheme and test it.
It also skip whitespace trailing test on .bumpversoin.cfg at bum2version
itself  adds trailing spaces and try to commit which fails.

Fix and test auto version numbering.

---

nbformat/validator.py

The code returns `changes, nbdict`, not the other way around.

Fix docs and type annotations for validator.normalize

---

nbformat/validator.py

This is more in accordance with `normalize`
```
Returns
-------
changes : int
number of changes in the notebooks
notebook : dict
deep-copy of the original object with relevant changes.
```

Fix deprecation warning suggestion

---

.github/workflows/tests.yml
.pre-commit-config.yaml
codecov.yml
pyproject.toml
tests/test_sign.py

Cleanup workflow, coverage config, pre-commit, and mypy.

More maintenance cleanup

---

nbformat/v4/convert.py
tests/test3_no_min_version.ipynb
tests/test_validator.py

#237 made some public notebooks unreadable. There is only one nbformat minor for v3, so there is no ambiguity here. It's more important for real notebooks to be readable than perfect validation be satisfied.
For example, this is linked from the nbviewer front page and started to fail because of #237: https://nbviewer.org/gist/fonnesbeck/2352771

Only require nbformat_minor for v4

---

nbformat/validator.py

There is no equivalent behavior in normalize, so I don't think this shouldn't have been deprecated along with the other normalizing steps. `relax_add_props` is purely related to validation, not normalization since no changes are made, it only changes what is checked. The case for it still exists and is still relevant (in nbconvert preprocessor validation), so I think it should be kept.
This change (respecting the deprecation in nbconvert) has caused notebooks to fail on nbviewer: https://nbviewer.org/github/ibtassam1/SQL_Vancouver/blob/03f9f1e5dbd2c3e13965c01d125f5c9ab371d696/Vancouver%20Public%20Services_v3.ipynb
Deprecation was added in #282

Undeprecate validate(nb, relax_add_props=True)

---

nbformat/reader.py

In almost all cases, it will be truncated, but in the few cases that parse_json is called with short invalid inputs, this prevents confusion about what actually got passed in.
Specifically, I ran into a case where nbformat was getting an empty string, rather than a valid JSON string, which produced the message
> Notebook does not appear to be JSON: ''...
which wrongly implies there is more to the input than there was.
It's a minor issue for sure, but I was poking around here anyway, so I thought I'd fix it.

Only add ellipsis to NotJSONError message if message is truncated

---

nbformat/validator.py

:wave: This update adds the `strip_invalid_metadata` argument to the public `normalize` method, passing the argument into the nonpublic `_normalize` method rather than always passing false.
The reason behind this change is that the _normalize method [only uses the `relax_add_props` argument when `strip_invalid_metadata` is true](https://github.com/jupyter/nbformat/blob/3bc1b535f40b55961fd3b44ff1b38df05e0a9eda/nbformat/validator.py#L374-L377).  That argument is currently hardcoded to false by `normalize`, making the `relax_add_props` argument functionality unused.  By allowing callers to specify `strip_invalid_metadata`, there is at least a chance that the `relax_add_prop` argument will also be used.
I didn't see any tests in this project related to the normalize method, so I wasn't sure …

Add strip_invalid_metadata argument to validator normalize method

---

nbformat/json_compat.py

`jsonschema` v4.18.0 deprecated
importing of `jsonschema.ErrorTree`
instead import it via `jsonschema.exceptions.ErrorTree`
https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0
This to avoid warning raised:
```
/usr/local/lib/python3.8/site-packages/nbformat/json_compat.py:14:Importing ErrorTree directly from the jsonschema package is deprecated and will become an ImportError. Import it from jsonschema.exceptions instead.
/usr/local/lib/python3.8/site-packages/nbformat/json_compat.py:14:Importing ErrorTree directly from the jsonschema package is deprecated and will become an ImportError. Import it from jsonschema.exceptions instead.
```

Fix deprecation warning when importing from jsonschema

---

pyproject.toml

This transforms the [nbformat page on PyPI](https://pypi.org/project/nbformat/) from this:
to something like this, although issues will instead be a direct link to the Git repo:

Improve project URLs that display on PyPI

---

.github/workflows/tests.yml
.pre-commit-config.yaml
.readthedocs.yaml
RELEASING.md
docs/conf.py
docs/format_description.rst
nbformat/_struct.py
nbformat/_version.py
nbformat/json_compat.py
nbformat/sign.py
nbformat/v2/__init__.py
nbformat/v3/__init__.py
nbformat/v3/nbbase.py
nbformat/v4/convert.py
nbformat/validator.py
package.json
pyproject.toml
tests/test_api.py
tests/test_validator.py
tests/v4/test_json.py

Adopt [pypi.org/project/sp-repo-review](https://pypi.org/project/sp-repo-review/), which has a standard set of checks for packages in the scientific python ecosystem, as seen in [learn.scientific-python.org/development](https://learn.scientific-python.org/development/).
This caught a bunch of rst formatting issues and general misspellings.

Adopt sp-repo-review

---

nbformat/sign.py

The code for that function originally predates the introduction of the function `jupyter_core.paths.jupyter_data_dir` which can now be used to determine the Jupyter data directory instead of initializing an instance of JupyterApp just to figure its data directory.
I figure this out while working on another PR for jupyter_server_fileid which uses the function to determine the data directory : https://github.com/jupyter-server/jupyter_server_fileid/blob/v0.9.0/jupyter_server_fileid/manager.py#L23

Simplify NotebookNotary._data_dir_default

---

nbformat/sign.py
package.json

Reverts https://github.com/jupyter/nbformat/pull/378 to close https://github.com/jupyter/nbformat/issues/396.
This is because the breakage was also reported in the wild, see:
- https://github.com/voila-dashboards/voila/issues/1450
- https://github.com/jupyterlab/jupyterlab/issues/15985

Revert PR #378 (Simplify NotebookNotary._data_dir_default)
